services:
  # Serviço Backend (API e Lógica de Agentes)
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - swarm_network

  # Serviço Frontend (Interface Streamlit)
  frontend:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_URL=http://backend:8000/api/chat
      - PYTHONPATH=/app
    volumes:
      - ./chroma_db:/app/chroma_db
    command: streamlit run app/frontend/main.py --server.address 0.0.0.0
    depends_on:
      - backend
    networks:
      - swarm_network

networks:
  swarm_network:
    driver: bridge